"""Fortalecer integridad e historial sin borrar datos operacionales.

Revision ID: 022_integridad_bd
Revises: 021a_saneamiento_historial

Definitions are frozen; this revision does not import application models.
Preflight aborts before DDL on incompatible historical records.
"""
from alembic import op
import sqlalchemy as sa

revision = "022_integridad_bd"
down_revision = "021b_estadias_consolidadas"
branch_labels = None
depends_on = None

# Cast the operand, not the column: support existing JSON and JSONB schemas.
NEUMATICO_UNICO = "CASE WHEN jsonb_typeof(ruedas::jsonb) = 'array' THEN jsonb_array_length(ruedas::jsonb) = 1 ELSE false END"

CHECKS = [('buses', 'ck_buses_litros', 'max_litros IS NULL OR max_litros >= 0'),
 ('buses', 'ck_buses_max', 'max IS NULL OR max >= 0'),
 ('buses', 'ck_buses_min', 'min IS NULL OR min >= 0'),
 ('buses', 'ck_buses_numero', 'n_bus IS NULL OR length(trim(n_bus)) > 0'),
 ('buses', 'ck_buses_patente', 'length(trim(patente)) > 0'),
 ('buses', 'ck_buses_rango', 'min IS NULL OR max IS NULL OR min <= max'),
 ('reportes_neumaticos', 'ck_neumaticos_rueda_unica', NEUMATICO_UNICO),
 ('taller_asignacion_fallas',
  'ck_asignaciones_duracion',
  'duracion_minutos IS NULL OR duracion_minutos >= 0'),
 ('taller_asignacion_fallas',
  'ck_asignaciones_fechas',
  'fecha_desasignacion IS NULL OR fecha_desasignacion >= fecha_asignacion'),
 ('taller_asignacion_fallas',
  'ck_asignaciones_origen',
  "origen IN ('SUPERVISOR','AUTOASIGNACION','MECANICO')"),
 ('taller_falla_eventos',
  'ck_eventos_estado_anterior',
  "estado_anterior IS NULL OR estado_anterior IN ('PENDIENTE','INCOMPLETA','RESUELTA')"),
 ('taller_falla_eventos',
  'ck_eventos_estado_nuevo',
  "estado_nuevo IS NULL OR estado_nuevo IN ('PENDIENTE','INCOMPLETA','RESUELTA')"),
 ('taller_falla_eventos',
  'ck_eventos_tipo',
  'tipo_evento IN '
  "('REPORTADA','RESUELTA','REABIERTA','INCOMPLETA','FALTA_REPUESTO_ACTIVADA','FALTA_REPUESTO_RETIRADA')"),
 ('taller_solicitud_comentarios',
  'ck_comentarios_tipo',
  'tipo IN '
  "('GENERAL','AVANCE','CIERRE','SISTEMA','CAMBIO_ESTADO','ASIGNACION','ENTREGA_TURNO','SALIDA_MECANICO','RESOLUCION','CHECKLIST','REAPERTURA','FALTA_REPUESTO','REPUESTO_DISPONIBLE','SUPERVISION')"),
 ('taller_solicitud_detalles', 'ck_detalles_estado', "estado IN ('PENDIENTE','INCOMPLETA','RESUELTA')"),
 ('taller_solicitud_detalles',
  'ck_detalles_fechas',
  'fecha_resolucion IS NULL OR fecha_resolucion >= fecha_creacion'),
 ('taller_solicitud_detalles', 'ck_detalles_resuelto_estado', "resuelto = (estado = 'RESUELTA')"),
 ('taller_solicitud_estadias', 'ck_estadias_fechas', 'fecha_salida IS NULL OR fecha_salida >= fecha_ingreso'),
 ('taller_solicitud_estadias', 'ck_estadias_horas', 'horas_estadia IS NULL OR horas_estadia >= 0'),
 ('taller_solicitud_estadias', 'ck_estadias_visita', 'numero_visita > 0'),
 ('taller_solicitud_evidencias', 'ck_evidencias_tamano', 'size_bytes IS NULL OR size_bytes >= 0'),
 ('taller_solicitud_mecanicos', 'ck_cuadrilla_duracion', 'duracion_minutos IS NULL OR duracion_minutos >= 0'),
 ('taller_solicitud_mecanicos',
  'ck_cuadrilla_fechas',
  'fecha_desasignacion IS NULL OR fecha_desasignacion >= fecha_asignacion'),
 ('taller_solicitud_pauta', 'ck_pauta_estado', "estado IN ('OK','DEFECTO','NO_APLICA')"),
 ('taller_solicitudes', 'ck_solicitudes_cierre', 'fecha_cierre IS NULL OR fecha_cierre >= fecha_creacion'),
 ('taller_solicitudes',
  'ck_solicitudes_demora',
  'horas_demora_primer_ingreso IS NULL OR horas_demora_primer_ingreso >= 0'),
 ('taller_solicitudes',
  'ck_solicitudes_estado',
  "estado IN ('REPORTADO','PENDIENTE','EN_REPARACION','LIBERADO','FINALIZADO')"),
 ('taller_solicitudes',
  'ck_solicitudes_horas',
  'horas_taller_acumuladas IS NULL OR horas_taller_acumuladas >= 0'),
 ('taller_solicitudes', 'ck_solicitudes_numero', 'length(trim(n_bus)) > 0')]

UNIQUES = [('taller_falla_evento_mecanicos', 'uq_evento_mecanico', ['evento_id', 'mecanico_id']),
 ('taller_solicitud_comentarios', 'uq_comentarios_id_solicitud', ['id', 'solicitud_id']),
 ('taller_solicitud_detalles', 'uq_detalles_id_solicitud', ['id', 'solicitud_id']),
 ('taller_solicitud_estadias', 'uq_estadia_visita', ['solicitud_id', 'numero_visita']),
 ('taller_solicitud_pauta', 'uq_solicitud_pauta_item', ['solicitud_id', 'item_id'])]

INDEXES = [('buses', 'ix_buses_n_bus', 'CREATE INDEX ix_buses_n_bus ON buses (n_bus)'),
 ('buses', 'ix_buses_patente', 'CREATE INDEX ix_buses_patente ON buses (patente)'),
 ('buses', 'ix_buses_usuario_baja_id', 'CREATE INDEX ix_buses_usuario_baja_id ON buses (usuario_baja_id)'),
 ('buses',
  'uq_buses_numero_normalizado',
  'CREATE UNIQUE INDEX uq_buses_numero_normalizado ON buses (lower(btrim(n_bus)))'),
 ('buses',
  'uq_buses_patente_normalizada',
  'CREATE UNIQUE INDEX uq_buses_patente_normalizada ON buses (upper(btrim(patente)))'),
 ('categorias_falla',
  'ix_categorias_falla_nombre',
  'CREATE UNIQUE INDEX ix_categorias_falla_nombre ON categorias_falla (nombre)'),
 ('fallas_taller',
  'ix_fallas_taller_cat_active',
  'CREATE INDEX ix_fallas_taller_cat_active ON fallas_taller (categoria_id, is_active)'),
 ('fallas_taller',
  'ix_fallas_taller_categoria_id',
  'CREATE INDEX ix_fallas_taller_categoria_id ON fallas_taller (categoria_id)'),
 ('pauta_taller_items',
  'ix_pauta_taller_items_categoria',
  'CREATE INDEX ix_pauta_taller_items_categoria ON pauta_taller_items (categoria)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_bus_id',
  'CREATE INDEX ix_reportes_neumaticos_bus_id ON reportes_neumaticos (bus_id)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_n_bus',
  'CREATE INDEX ix_reportes_neumaticos_n_bus ON reportes_neumaticos (n_bus)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_usuario_id',
  'CREATE INDEX ix_reportes_neumaticos_usuario_id ON reportes_neumaticos (usuario_id)'),
 ('roles', 'ix_roles_nombre', 'CREATE UNIQUE INDEX ix_roles_nombre ON roles (nombre)'),
 ('taller_asignacion_fallas',
  'ix_asig_fallas_mec_activo',
  'CREATE INDEX ix_asig_fallas_mec_activo ON taller_asignacion_fallas (mecanico_id, is_activo)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_asignado_por_id',
  'CREATE INDEX ix_taller_asignacion_fallas_asignado_por_id ON taller_asignacion_fallas (asignado_por_id)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_detalle_id',
  'CREATE INDEX ix_taller_asignacion_fallas_detalle_id ON taller_asignacion_fallas (detalle_id)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_is_activo',
  'CREATE INDEX ix_taller_asignacion_fallas_is_activo ON taller_asignacion_fallas (is_activo)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_mecanico_id',
  'CREATE INDEX ix_taller_asignacion_fallas_mecanico_id ON taller_asignacion_fallas (mecanico_id)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_solicitud_id',
  'CREATE INDEX ix_taller_asignacion_fallas_solicitud_id ON taller_asignacion_fallas (solicitud_id)'),
 ('taller_asignacion_fallas',
  'uq_asignacion_falla_activa',
  'CREATE UNIQUE INDEX uq_asignacion_falla_activa ON taller_asignacion_fallas (detalle_id, mecanico_id) '
  'WHERE is_activo = true'),
 ('taller_falla_evento_mecanicos',
  'ix_taller_falla_evento_mecanicos_evento_id',
  'CREATE INDEX ix_taller_falla_evento_mecanicos_evento_id ON taller_falla_evento_mecanicos (evento_id)'),
 ('taller_falla_evento_mecanicos',
  'ix_taller_falla_evento_mecanicos_mecanico_id',
  'CREATE INDEX ix_taller_falla_evento_mecanicos_mecanico_id ON taller_falla_evento_mecanicos (mecanico_id)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_detalle_id',
  'CREATE INDEX ix_taller_falla_eventos_detalle_id ON taller_falla_eventos (detalle_id)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_fecha_evento',
  'CREATE INDEX ix_taller_falla_eventos_fecha_evento ON taller_falla_eventos (fecha_evento)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_tipo_evento',
  'CREATE INDEX ix_taller_falla_eventos_tipo_evento ON taller_falla_eventos (tipo_evento)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_usuario_actor_id',
  'CREATE INDEX ix_taller_falla_eventos_usuario_actor_id ON taller_falla_eventos (usuario_actor_id)'),
 ('taller_solicitud_comentarios',
  'ix_taller_solicitud_comentarios_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_comentarios_solicitud_id ON taller_solicitud_comentarios (solicitud_id)'),
 ('taller_solicitud_comentarios',
  'ix_taller_solicitud_comentarios_usuario_id',
  'CREATE INDEX ix_taller_solicitud_comentarios_usuario_id ON taller_solicitud_comentarios (usuario_id)'),
 ('taller_solicitud_detalles',
  'ix_sol_detalles_sol_resuelto',
  'CREATE INDEX ix_sol_detalles_sol_resuelto ON taller_solicitud_detalles (solicitud_id, resuelto)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_estado',
  'CREATE INDEX ix_taller_solicitud_detalles_estado ON taller_solicitud_detalles (estado)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_falla_id',
  'CREATE INDEX ix_taller_solicitud_detalles_falla_id ON taller_solicitud_detalles (falla_id)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_fecha_reporte',
  'CREATE INDEX ix_taller_solicitud_detalles_fecha_reporte ON taller_solicitud_detalles (fecha_reporte)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_mecanico_resolvio_id',
  'CREATE INDEX ix_taller_solicitud_detalles_mecanico_resolvio_id ON taller_solicitud_detalles '
  '(mecanico_resolvio_id)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_reportado_por_id',
  'CREATE INDEX ix_taller_solicitud_detalles_reportado_por_id ON taller_solicitud_detalles '
  '(reportado_por_id)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_solicitud_fecha_reporte',
  'CREATE INDEX ix_taller_solicitud_detalles_solicitud_fecha_reporte ON taller_solicitud_detalles '
  '(solicitud_id, fecha_reporte)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_detalles_solicitud_id ON taller_solicitud_detalles (solicitud_id)'),
 ('taller_solicitud_estadias',
  'ix_taller_solicitud_estadias_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_estadias_solicitud_id ON taller_solicitud_estadias (solicitud_id)'),
 ('taller_solicitud_estadias',
  'uq_estadia_abierta',
  'CREATE UNIQUE INDEX uq_estadia_abierta ON taller_solicitud_estadias (solicitud_id) WHERE fecha_salida IS '
  'NULL'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_comentario_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_comentario_id ON taller_solicitud_evidencias (comentario_id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_detalle_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_detalle_id ON taller_solicitud_evidencias (detalle_id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_solicitud_id ON taller_solicitud_evidencias (solicitud_id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_usuario_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_usuario_id ON taller_solicitud_evidencias (usuario_id)'),
 ('taller_solicitud_mecanicos',
  'ix_sol_mecanicos_mec_activo',
  'CREATE INDEX ix_sol_mecanicos_mec_activo ON taller_solicitud_mecanicos (mecanico_id, is_activo)'),
 ('taller_solicitud_mecanicos',
  'ix_taller_solicitud_mecanicos_asignado_por_id',
  'CREATE INDEX ix_taller_solicitud_mecanicos_asignado_por_id ON taller_solicitud_mecanicos '
  '(asignado_por_id)'),
 ('taller_solicitud_mecanicos',
  'ix_taller_solicitud_mecanicos_mecanico_id',
  'CREATE INDEX ix_taller_solicitud_mecanicos_mecanico_id ON taller_solicitud_mecanicos (mecanico_id)'),
 ('taller_solicitud_mecanicos',
  'ix_taller_solicitud_mecanicos_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_mecanicos_solicitud_id ON taller_solicitud_mecanicos (solicitud_id)'),
 ('taller_solicitud_mecanicos',
  'uq_cuadrilla_activa',
  'CREATE UNIQUE INDEX uq_cuadrilla_activa ON taller_solicitud_mecanicos (solicitud_id, mecanico_id) WHERE '
  'is_activo = true'),
 ('taller_solicitud_pauta',
  'ix_taller_solicitud_pauta_item_id',
  'CREATE INDEX ix_taller_solicitud_pauta_item_id ON taller_solicitud_pauta (item_id)'),
 ('taller_solicitud_pauta',
  'ix_taller_solicitud_pauta_mecanico_id',
  'CREATE INDEX ix_taller_solicitud_pauta_mecanico_id ON taller_solicitud_pauta (mecanico_id)'),
 ('taller_solicitud_pauta',
  'ix_taller_solicitud_pauta_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_pauta_solicitud_id ON taller_solicitud_pauta (solicitud_id)'),
 ('taller_solicitudes',
  'ix_solicitudes_estado_fecha',
  'CREATE INDEX ix_solicitudes_estado_fecha ON taller_solicitudes (estado, fecha_creacion)'),
 ('taller_solicitudes',
  'ix_solicitudes_fecha_creacion',
  'CREATE INDEX ix_solicitudes_fecha_creacion ON taller_solicitudes (fecha_creacion)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_bus_id',
  'CREATE INDEX ix_taller_solicitudes_bus_id ON taller_solicitudes (bus_id)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_estado',
  'CREATE INDEX ix_taller_solicitudes_estado ON taller_solicitudes (estado)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_fecha_actualizacion',
  'CREATE INDEX ix_taller_solicitudes_fecha_actualizacion ON taller_solicitudes (fecha_actualizacion)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_fecha_liberacion',
  'CREATE INDEX ix_taller_solicitudes_fecha_liberacion ON taller_solicitudes (fecha_liberacion)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_fecha_primer_ingreso_taller',
  'CREATE INDEX ix_taller_solicitudes_fecha_primer_ingreso_taller ON taller_solicitudes '
  '(fecha_primer_ingreso_taller)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_mecanico_cierre_id',
  'CREATE INDEX ix_taller_solicitudes_mecanico_cierre_id ON taller_solicitudes (mecanico_cierre_id)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_n_bus',
  'CREATE INDEX ix_taller_solicitudes_n_bus ON taller_solicitudes (n_bus)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_usuario_creador_id',
  'CREATE INDEX ix_taller_solicitudes_usuario_creador_id ON taller_solicitudes (usuario_creador_id)'),
 ('taller_solicitudes',
  'uq_taller_solicitudes_bus_activa',
  'CREATE UNIQUE INDEX uq_taller_solicitudes_bus_activa ON taller_solicitudes (bus_id) WHERE bus_id IS NOT '
  "NULL AND estado <> 'FINALIZADO'"),
 ('taller_solicitudes',
  'uq_taller_solicitudes_n_bus_activa_sin_bus_id',
  'CREATE UNIQUE INDEX uq_taller_solicitudes_n_bus_activa_sin_bus_id ON taller_solicitudes '
  "(lower(btrim(n_bus))) WHERE bus_id IS NULL AND estado <> 'FINALIZADO'"),
 ('usuarios', 'ix_usuarios_rol_id', 'CREATE INDEX ix_usuarios_rol_id ON usuarios (rol_id)'),
 ('usuarios', 'ix_usuarios_username', 'CREATE UNIQUE INDEX ix_usuarios_username ON usuarios (username)')]

FOREIGN_KEYS = [('buses', 'fk_buses_usuario_baja_id', ['usuario_baja_id'], 'usuarios', ['id'], 'SET NULL'),
 ('fallas_taller', 'fk_fallas_taller_categoria_id', ['categoria_id'], 'categorias_falla', ['id'], 'RESTRICT'),
 ('reportes_neumaticos', 'fk_reportes_neumaticos_bus_id', ['bus_id'], 'buses', ['id'], 'SET NULL'),
 ('reportes_neumaticos', 'fk_reportes_neumaticos_usuario_id', ['usuario_id'], 'usuarios', ['id'], 'SET NULL'),
 ('taller_asignacion_fallas',
  'fk_asignaciones_detalle_ot',
  ['detalle_id', 'solicitud_id'],
  'taller_solicitud_detalles',
  ['id', 'solicitud_id'],
  'RESTRICT'),
 ('taller_asignacion_fallas',
  'fk_taller_asignacion_fallas_asignado_por_id',
  ['asignado_por_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_asignacion_fallas',
  'fk_taller_asignacion_fallas_mecanico_id',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_asignacion_fallas',
  'fk_taller_asignacion_fallas_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_falla_evento_mecanicos',
  'fk_taller_falla_evento_mecanicos_evento_id',
  ['evento_id'],
  'taller_falla_eventos',
  ['id'],
  'RESTRICT'),
 ('taller_falla_evento_mecanicos',
  'fk_taller_falla_evento_mecanicos_mecanico_id',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_falla_eventos',
  'fk_taller_falla_eventos_detalle_id',
  ['detalle_id'],
  'taller_solicitud_detalles',
  ['id'],
  'RESTRICT'),
 ('taller_falla_eventos',
  'fk_taller_falla_eventos_usuario_actor_id',
  ['usuario_actor_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_comentarios',
  'fk_taller_solicitud_comentarios_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_comentarios',
  'fk_taller_solicitud_comentarios_usuario_id',
  ['usuario_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_detalles',
  'fk_taller_solicitud_detalles_falla_id',
  ['falla_id'],
  'fallas_taller',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_detalles',
  'fk_taller_solicitud_detalles_mecanico_resolvio_id',
  ['mecanico_resolvio_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_detalles',
  'fk_taller_solicitud_detalles_reportado_por_id',
  ['reportado_por_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_detalles',
  'fk_taller_solicitud_detalles_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_estadias',
  'fk_taller_solicitud_estadias_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_evidencias',
  'fk_evidencias_comentario_ot',
  ['comentario_id', 'solicitud_id'],
  'taller_solicitud_comentarios',
  ['id', 'solicitud_id'],
  'RESTRICT'),
 ('taller_solicitud_evidencias',
  'fk_evidencias_detalle_ot',
  ['detalle_id', 'solicitud_id'],
  'taller_solicitud_detalles',
  ['id', 'solicitud_id'],
  'RESTRICT'),
 ('taller_solicitud_evidencias',
  'fk_taller_solicitud_evidencias_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_evidencias',
  'fk_taller_solicitud_evidencias_usuario_id',
  ['usuario_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_mecanicos',
  'fk_taller_solicitud_mecanicos_asignado_por_id',
  ['asignado_por_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_mecanicos',
  'fk_taller_solicitud_mecanicos_mecanico_id',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_mecanicos',
  'fk_taller_solicitud_mecanicos_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_pauta',
  'fk_taller_solicitud_pauta_item_id',
  ['item_id'],
  'pauta_taller_items',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_pauta',
  'fk_taller_solicitud_pauta_mecanico_id',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitud_pauta',
  'fk_taller_solicitud_pauta_solicitud_id',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'RESTRICT'),
 ('taller_solicitudes', 'fk_taller_solicitudes_bus_id', ['bus_id'], 'buses', ['id'], 'RESTRICT'),
 ('taller_solicitudes',
  'fk_taller_solicitudes_mecanico_cierre_id',
  ['mecanico_cierre_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('taller_solicitudes',
  'fk_taller_solicitudes_usuario_creador_id',
  ['usuario_creador_id'],
  'usuarios',
  ['id'],
  'RESTRICT'),
 ('usuarios', 'fk_usuarios_rol_id', ['rol_id'], 'roles', ['id'], 'RESTRICT')]

OLD_FOREIGN_KEYS = [('buses', 'buses_usuario_baja_id_fkey', ['usuario_baja_id'], 'usuarios', ['id'], 'SET NULL'),
 ('fallas_taller',
  'fallas_taller_categoria_id_fkey',
  ['categoria_id'],
  'categorias_falla',
  ['id'],
  'CASCADE'),
 ('reportes_neumaticos', 'fk_reportes_neumaticos_bus_id', ['bus_id'], 'buses', ['id'], 'SET NULL'),
 ('reportes_neumaticos',
  'reportes_neumaticos_usuario_id_fkey',
  ['usuario_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_asignacion_fallas',
  'taller_asignacion_fallas_asignado_por_id_fkey',
  ['asignado_por_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_asignacion_fallas',
  'taller_asignacion_fallas_detalle_id_fkey',
  ['detalle_id'],
  'taller_solicitud_detalles',
  ['id'],
  'CASCADE'),
 ('taller_asignacion_fallas',
  'taller_asignacion_fallas_mecanico_id_fkey',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'CASCADE'),
 ('taller_asignacion_fallas',
  'taller_asignacion_fallas_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_falla_evento_mecanicos',
  'taller_falla_evento_mecanicos_evento_id_fkey',
  ['evento_id'],
  'taller_falla_eventos',
  ['id'],
  'CASCADE'),
 ('taller_falla_evento_mecanicos',
  'taller_falla_evento_mecanicos_mecanico_id_fkey',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_falla_eventos',
  'taller_falla_eventos_detalle_id_fkey',
  ['detalle_id'],
  'taller_solicitud_detalles',
  ['id'],
  'CASCADE'),
 ('taller_falla_eventos',
  'taller_falla_eventos_usuario_actor_id_fkey',
  ['usuario_actor_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_comentarios',
  'taller_solicitud_comentarios_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_comentarios',
  'taller_solicitud_comentarios_usuario_id_fkey',
  ['usuario_id'],
  'usuarios',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_detalles',
  'fk_taller_solicitud_detalles_reportado_por_id',
  ['reportado_por_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_detalles',
  'taller_solicitud_detalles_falla_id_fkey',
  ['falla_id'],
  'fallas_taller',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_detalles',
  'taller_solicitud_detalles_mecanico_resolvio_id_fkey',
  ['mecanico_resolvio_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_detalles',
  'taller_solicitud_detalles_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_estadias',
  'taller_solicitud_estadias_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_evidencias',
  'fk_taller_solicitud_evidencias_comentario_id',
  ['comentario_id'],
  'taller_solicitud_comentarios',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_evidencias',
  'taller_solicitud_evidencias_detalle_id_fkey',
  ['detalle_id'],
  'taller_solicitud_detalles',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_evidencias',
  'taller_solicitud_evidencias_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_evidencias',
  'taller_solicitud_evidencias_usuario_id_fkey',
  ['usuario_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_mecanicos',
  'taller_solicitud_mecanicos_asignado_por_id_fkey',
  ['asignado_por_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_mecanicos',
  'taller_solicitud_mecanicos_mecanico_id_fkey',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_mecanicos',
  'taller_solicitud_mecanicos_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_pauta',
  'taller_solicitud_pauta_item_id_fkey',
  ['item_id'],
  'pauta_taller_items',
  ['id'],
  'CASCADE'),
 ('taller_solicitud_pauta',
  'taller_solicitud_pauta_mecanico_id_fkey',
  ['mecanico_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitud_pauta',
  'taller_solicitud_pauta_solicitud_id_fkey',
  ['solicitud_id'],
  'taller_solicitudes',
  ['id'],
  'CASCADE'),
 ('taller_solicitudes', 'fk_taller_solicitudes_bus_id', ['bus_id'], 'buses', ['id'], 'SET NULL'),
 ('taller_solicitudes',
  'taller_solicitudes_mecanico_cierre_id_fkey',
  ['mecanico_cierre_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('taller_solicitudes',
  'taller_solicitudes_usuario_creador_id_fkey',
  ['usuario_creador_id'],
  'usuarios',
  ['id'],
  'SET NULL'),
 ('usuarios', 'usuarios_rol_id_fkey', ['rol_id'], 'roles', ['id'], 'RESTRICT')]

DEFAULTS = [('categorias_falla', 'is_active', "'true'", 'true'),
 ('fallas_taller', 'is_active', "'true'", 'true'),
 ('pauta_taller_items', 'is_active', "'true'", 'true'),
 ('pauta_taller_items', 'orden', "'0'", '0'),
 ('taller_asignacion_fallas', 'is_activo', "'true'", 'true'),
 ('taller_asignacion_fallas', 'origen', "'SUPERVISOR'", "'SUPERVISOR'::character varying"),
 ('taller_asignacion_fallas', 'resuelto_en_esta_asignacion', "'false'", 'false'),
 ('taller_falla_eventos', 'fecha_evento', 'now()', None),
 ('taller_solicitud_comentarios', 'tipo', "'GENERAL'", "'GENERAL'::character varying"),
 ('taller_solicitud_detalles', 'estado', "'PENDIENTE'", "'PENDIENTE'::character varying"),
 ('taller_solicitud_detalles', 'falta_repuesto', "'false'", 'false'),
 ('taller_solicitud_detalles', 'resuelto', "'false'", 'false'),
 ('taller_solicitud_estadias', 'numero_visita', "'1'", None),
 ('taller_solicitud_mecanicos', 'es_lider_responsable', "'false'", 'false'),
 ('taller_solicitud_mecanicos', 'is_activo', "'true'", 'true'),
 ('taller_solicitudes', 'estado', "'PENDIENTE'", "'REPORTADO'::character varying"),
 ('taller_solicitudes', 'horas_taller_acumuladas', None, '0.0')]

OLD_INDEXES = [('buses', 'ix_buses_en_taller', 'CREATE INDEX ix_buses_en_taller ON public.buses USING btree (en_taller)'),
 ('buses', 'ix_buses_id', 'CREATE INDEX ix_buses_id ON public.buses USING btree (id)'),
 ('buses', 'ix_buses_is_active', 'CREATE INDEX ix_buses_is_active ON public.buses USING btree (is_active)'),
 ('buses', 'ix_buses_n_bus', 'CREATE INDEX ix_buses_n_bus ON public.buses USING btree (n_bus)'),
 ('buses', 'ix_buses_patente', 'CREATE INDEX ix_buses_patente ON public.buses USING btree (patente)'),
 ('buses',
  'ix_buses_usuario_baja_id',
  'CREATE INDEX ix_buses_usuario_baja_id ON public.buses USING btree (usuario_baja_id)'),
 ('categorias_falla',
  'ix_categorias_falla_active',
  'CREATE INDEX ix_categorias_falla_active ON public.categorias_falla USING btree (is_active)'),
 ('categorias_falla',
  'ix_categorias_falla_id',
  'CREATE INDEX ix_categorias_falla_id ON public.categorias_falla USING btree (id)'),
 ('categorias_falla',
  'ix_categorias_falla_nombre',
  'CREATE UNIQUE INDEX ix_categorias_falla_nombre ON public.categorias_falla USING btree (nombre)'),
 ('fallas_taller',
  'ix_fallas_taller_cat_active',
  'CREATE INDEX ix_fallas_taller_cat_active ON public.fallas_taller USING btree (categoria_id, is_active)'),
 ('fallas_taller',
  'ix_fallas_taller_categoria_id',
  'CREATE INDEX ix_fallas_taller_categoria_id ON public.fallas_taller USING btree (categoria_id)'),
 ('fallas_taller',
  'ix_fallas_taller_id',
  'CREATE INDEX ix_fallas_taller_id ON public.fallas_taller USING btree (id)'),
 ('pauta_taller_items',
  'ix_pauta_taller_items_categoria',
  'CREATE INDEX ix_pauta_taller_items_categoria ON public.pauta_taller_items USING btree (categoria)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_bus_id',
  'CREATE INDEX ix_reportes_neumaticos_bus_id ON public.reportes_neumaticos USING btree (bus_id)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_id',
  'CREATE INDEX ix_reportes_neumaticos_id ON public.reportes_neumaticos USING btree (id)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_n_bus',
  'CREATE INDEX ix_reportes_neumaticos_n_bus ON public.reportes_neumaticos USING btree (n_bus)'),
 ('reportes_neumaticos',
  'ix_reportes_neumaticos_usuario_id',
  'CREATE INDEX ix_reportes_neumaticos_usuario_id ON public.reportes_neumaticos USING btree (usuario_id)'),
 ('roles', 'ix_roles_id', 'CREATE INDEX ix_roles_id ON public.roles USING btree (id)'),
 ('roles', 'ix_roles_nombre', 'CREATE UNIQUE INDEX ix_roles_nombre ON public.roles USING btree (nombre)'),
 ('taller_asignacion_fallas',
  'ix_asig_fallas_mec_activo',
  'CREATE INDEX ix_asig_fallas_mec_activo ON public.taller_asignacion_fallas USING btree (mecanico_id, '
  'is_activo)'),
 ('taller_asignacion_fallas',
  'ix_asig_fallas_solicitud',
  'CREATE INDEX ix_asig_fallas_solicitud ON public.taller_asignacion_fallas USING btree (solicitud_id)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_detalle_id',
  'CREATE INDEX ix_taller_asignacion_fallas_detalle_id ON public.taller_asignacion_fallas USING btree '
  '(detalle_id)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_is_activo',
  'CREATE INDEX ix_taller_asignacion_fallas_is_activo ON public.taller_asignacion_fallas USING btree '
  '(is_activo)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_mecanico_id',
  'CREATE INDEX ix_taller_asignacion_fallas_mecanico_id ON public.taller_asignacion_fallas USING btree '
  '(mecanico_id)'),
 ('taller_asignacion_fallas',
  'ix_taller_asignacion_fallas_solicitud_id',
  'CREATE INDEX ix_taller_asignacion_fallas_solicitud_id ON public.taller_asignacion_fallas USING btree '
  '(solicitud_id)'),
 ('taller_falla_evento_mecanicos',
  'ix_taller_falla_evento_mecanicos_evento_id',
  'CREATE INDEX ix_taller_falla_evento_mecanicos_evento_id ON public.taller_falla_evento_mecanicos USING '
  'btree (evento_id)'),
 ('taller_falla_evento_mecanicos',
  'ix_taller_falla_evento_mecanicos_mecanico_id',
  'CREATE INDEX ix_taller_falla_evento_mecanicos_mecanico_id ON public.taller_falla_evento_mecanicos USING '
  'btree (mecanico_id)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_detalle_id',
  'CREATE INDEX ix_taller_falla_eventos_detalle_id ON public.taller_falla_eventos USING btree (detalle_id)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_fecha_evento',
  'CREATE INDEX ix_taller_falla_eventos_fecha_evento ON public.taller_falla_eventos USING btree '
  '(fecha_evento)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_tipo_evento',
  'CREATE INDEX ix_taller_falla_eventos_tipo_evento ON public.taller_falla_eventos USING btree '
  '(tipo_evento)'),
 ('taller_falla_eventos',
  'ix_taller_falla_eventos_usuario_actor_id',
  'CREATE INDEX ix_taller_falla_eventos_usuario_actor_id ON public.taller_falla_eventos USING btree '
  '(usuario_actor_id)'),
 ('taller_solicitud_comentarios',
  'ix_taller_solicitud_comentarios_id',
  'CREATE INDEX ix_taller_solicitud_comentarios_id ON public.taller_solicitud_comentarios USING btree (id)'),
 ('taller_solicitud_comentarios',
  'ix_taller_solicitud_comentarios_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_comentarios_solicitud_id ON public.taller_solicitud_comentarios USING '
  'btree (solicitud_id)'),
 ('taller_solicitud_detalles',
  'ix_sol_detalles_mecanico_resolvio',
  'CREATE INDEX ix_sol_detalles_mecanico_resolvio ON public.taller_solicitud_detalles USING btree '
  '(mecanico_resolvio_id)'),
 ('taller_solicitud_detalles',
  'ix_sol_detalles_sol_resuelto',
  'CREATE INDEX ix_sol_detalles_sol_resuelto ON public.taller_solicitud_detalles USING btree (solicitud_id, '
  'resuelto)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_estado',
  'CREATE INDEX ix_taller_solicitud_detalles_estado ON public.taller_solicitud_detalles USING btree '
  '(estado)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_id',
  'CREATE INDEX ix_taller_solicitud_detalles_id ON public.taller_solicitud_detalles USING btree (id)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_reportado_por_id',
  'CREATE INDEX ix_taller_solicitud_detalles_reportado_por_id ON public.taller_solicitud_detalles USING '
  'btree (reportado_por_id)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_solicitud_fecha_reporte',
  'CREATE INDEX ix_taller_solicitud_detalles_solicitud_fecha_reporte ON public.taller_solicitud_detalles '
  'USING btree (solicitud_id, fecha_reporte)'),
 ('taller_solicitud_detalles',
  'ix_taller_solicitud_detalles_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_detalles_solicitud_id ON public.taller_solicitud_detalles USING btree '
  '(solicitud_id)'),
 ('taller_solicitud_estadias',
  'ix_taller_solicitud_estadias_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_estadias_solicitud_id ON public.taller_solicitud_estadias USING btree '
  '(solicitud_id)'),
 ('taller_solicitud_estadias',
  'ix_taller_solicitud_estadias_solicitud_visita',
  'CREATE INDEX ix_taller_solicitud_estadias_solicitud_visita ON public.taller_solicitud_estadias USING '
  'btree (solicitud_id, numero_visita)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_comentario_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_comentario_id ON public.taller_solicitud_evidencias USING '
  'btree (comentario_id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_detalle_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_detalle_id ON public.taller_solicitud_evidencias USING btree '
  '(detalle_id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_id ON public.taller_solicitud_evidencias USING btree (id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_solicitud_id ON public.taller_solicitud_evidencias USING '
  'btree (solicitud_id)'),
 ('taller_solicitud_evidencias',
  'ix_taller_solicitud_evidencias_usuario_id',
  'CREATE INDEX ix_taller_solicitud_evidencias_usuario_id ON public.taller_solicitud_evidencias USING btree '
  '(usuario_id)'),
 ('taller_solicitud_mecanicos',
  'ix_sol_mecanicos_mec_activo',
  'CREATE INDEX ix_sol_mecanicos_mec_activo ON public.taller_solicitud_mecanicos USING btree (mecanico_id, '
  'is_activo)'),
 ('taller_solicitud_mecanicos',
  'ix_taller_solicitud_mecanicos_id',
  'CREATE INDEX ix_taller_solicitud_mecanicos_id ON public.taller_solicitud_mecanicos USING btree (id)'),
 ('taller_solicitud_mecanicos',
  'ix_taller_solicitud_mecanicos_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_mecanicos_solicitud_id ON public.taller_solicitud_mecanicos USING btree '
  '(solicitud_id)'),
 ('taller_solicitud_pauta',
  'ix_taller_solicitud_pauta_item_id',
  'CREATE INDEX ix_taller_solicitud_pauta_item_id ON public.taller_solicitud_pauta USING btree (item_id)'),
 ('taller_solicitud_pauta',
  'ix_taller_solicitud_pauta_solicitud_id',
  'CREATE INDEX ix_taller_solicitud_pauta_solicitud_id ON public.taller_solicitud_pauta USING btree '
  '(solicitud_id)'),
 ('taller_solicitudes',
  'ix_solicitudes_estado_fecha',
  'CREATE INDEX ix_solicitudes_estado_fecha ON public.taller_solicitudes USING btree (estado, '
  'fecha_creacion)'),
 ('taller_solicitudes',
  'ix_solicitudes_fecha_creacion',
  'CREATE INDEX ix_solicitudes_fecha_creacion ON public.taller_solicitudes USING btree (fecha_creacion)'),
 ('taller_solicitudes',
  'ix_solicitudes_mecanico_cierre',
  'CREATE INDEX ix_solicitudes_mecanico_cierre ON public.taller_solicitudes USING btree '
  '(mecanico_cierre_id)'),
 ('taller_solicitudes',
  'ix_solicitudes_n_bus',
  'CREATE INDEX ix_solicitudes_n_bus ON public.taller_solicitudes USING btree (n_bus)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_bus_id',
  'CREATE INDEX ix_taller_solicitudes_bus_id ON public.taller_solicitudes USING btree (bus_id)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_estado',
  'CREATE INDEX ix_taller_solicitudes_estado ON public.taller_solicitudes USING btree (estado)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_fecha_actualizacion',
  'CREATE INDEX ix_taller_solicitudes_fecha_actualizacion ON public.taller_solicitudes USING btree '
  '(fecha_actualizacion)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_fecha_liberacion',
  'CREATE INDEX ix_taller_solicitudes_fecha_liberacion ON public.taller_solicitudes USING btree '
  '(fecha_liberacion)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_fecha_primer_ingreso',
  'CREATE INDEX ix_taller_solicitudes_fecha_primer_ingreso ON public.taller_solicitudes USING btree '
  '(fecha_primer_ingreso_taller)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_id',
  'CREATE INDEX ix_taller_solicitudes_id ON public.taller_solicitudes USING btree (id)'),
 ('taller_solicitudes',
  'ix_taller_solicitudes_n_bus',
  'CREATE INDEX ix_taller_solicitudes_n_bus ON public.taller_solicitudes USING btree (n_bus)'),
 ('taller_solicitudes',
  'uq_taller_solicitudes_bus_activa',
  'CREATE UNIQUE INDEX uq_taller_solicitudes_bus_activa ON public.taller_solicitudes USING btree (bus_id) '
  "WHERE ((bus_id IS NOT NULL) AND ((estado)::text <> 'FINALIZADO'::text))"),
 ('taller_solicitudes',
  'uq_taller_solicitudes_n_bus_activa_sin_bus_id',
  'CREATE UNIQUE INDEX uq_taller_solicitudes_n_bus_activa_sin_bus_id ON public.taller_solicitudes USING '
  "btree (lower(TRIM(BOTH FROM n_bus))) WHERE ((bus_id IS NULL) AND ((estado)::text <> 'FINALIZADO'::text))"),
 ('usuarios', 'ix_usuarios_id', 'CREATE INDEX ix_usuarios_id ON public.usuarios USING btree (id)'),
 ('usuarios',
  'ix_usuarios_is_active',
  'CREATE INDEX ix_usuarios_is_active ON public.usuarios USING btree (is_active)'),
 ('usuarios',
  'ix_usuarios_rol_id',
  'CREATE INDEX ix_usuarios_rol_id ON public.usuarios USING btree (rol_id)'),
 ('usuarios',
  'ix_usuarios_username',
  'CREATE UNIQUE INDEX ix_usuarios_username ON public.usuarios USING btree (username)')]

DUPLICATE_UNIQUES = [('buses', 'uq_buses_nbus', ['n_bus']),
 ('categorias_falla', 'categorias_falla_nombre_key', ['nombre']),
 ('roles', 'roles_nombre_key', ['nombre'])]

FOREIGN_KEYS.append(('reportes_neumaticos', 'fk_neumaticos_reporte_origen', ['reporte_origen_id'], 'reportes_neumaticos', ['id'], 'RESTRICT'))
OLD_FOREIGN_KEYS.append(('reportes_neumaticos', 'fk_neumaticos_reporte_origen', ['reporte_origen_id'], 'reportes_neumaticos', ['id'], 'RESTRICT'))


def audit(connection):
    """SELECT-only checks usable before deployment; returns rule and record counts."""
    findings = []
    for table, name, expression in CHECKS:
        if name == 'ck_asignaciones_origen':
            expression = expression.replace("'SUPERVISOR'", "'SUPERVISOR','SUPERVISION'")
        count = connection.scalar(sa.text(f'SELECT count(*) FROM "{table}" WHERE ({expression}) IS FALSE'))
        if count:
            findings.append((name, count))
    for name, query in DUPLICATE_QUERIES:
        count = connection.scalar(sa.text(query))
        if count:
            findings.append((name, count))
    return findings


DUPLICATE_QUERIES = [
    ('cuadrilla_activa_duplicada', 'SELECT count(*) FROM (SELECT 1 FROM taller_solicitud_mecanicos WHERE is_activo GROUP BY solicitud_id,mecanico_id HAVING count(*) > 1) d'),
    ('asignacion_activa_duplicada', 'SELECT count(*) FROM (SELECT 1 FROM taller_asignacion_fallas WHERE is_activo GROUP BY detalle_id,mecanico_id HAVING count(*) > 1) d'),
    ('estadia_abierta_duplicada', 'SELECT count(*) FROM (SELECT 1 FROM taller_solicitud_estadias WHERE fecha_salida IS NULL GROUP BY solicitud_id HAVING count(*) > 1) d'),
    ('visita_duplicada', 'SELECT count(*) FROM (SELECT 1 FROM taller_solicitud_estadias GROUP BY solicitud_id,numero_visita HAVING count(*) > 1) d'),
    ('participante_evento_duplicado', 'SELECT count(*) FROM (SELECT 1 FROM taller_falla_evento_mecanicos WHERE mecanico_id IS NOT NULL GROUP BY evento_id,mecanico_id HAVING count(*) > 1) d'),
    ('patente_duplicada', 'SELECT count(*) FROM (SELECT 1 FROM buses GROUP BY upper(trim(patente)) HAVING count(*) > 1) d'),
    ('numero_bus_duplicado', 'SELECT count(*) FROM (SELECT 1 FROM buses WHERE n_bus IS NOT NULL GROUP BY lower(trim(n_bus)) HAVING count(*) > 1) d'),
    ('bus_activo_nulo', 'SELECT count(*) FROM buses WHERE is_active IS NULL'),
    ('rol_usuario_nulo', 'SELECT count(*) FROM usuarios WHERE rol_id IS NULL'),
    ('asignacion_ot_distinta', 'SELECT count(*) FROM taller_asignacion_fallas a JOIN taller_solicitud_detalles d ON d.id=a.detalle_id WHERE a.solicitud_id <> d.solicitud_id'),
    ('evidencia_detalle_ot_distinta', 'SELECT count(*) FROM taller_solicitud_evidencias e JOIN taller_solicitud_detalles d ON d.id=e.detalle_id WHERE e.solicitud_id <> d.solicitud_id'),
    ('evidencia_comentario_ot_distinta', 'SELECT count(*) FROM taller_solicitud_evidencias e JOIN taller_solicitud_comentarios c ON c.id=e.comentario_id WHERE e.solicitud_id <> c.solicitud_id'),
]


def _require_postgres(connection):
    if connection.dialect.name != 'postgresql':
        raise RuntimeError('La migración 022 requiere PostgreSQL; SQLite solo se usa para pruebas ORM')


def _replace_foreign_keys(definitions):
    inspector = sa.inspect(op.get_bind())
    tables = {entry[0] for entry in definitions}
    for table in sorted(tables):
        for fk in inspector.get_foreign_keys(table):
            op.drop_constraint(fk['name'], table, type_='foreignkey')
    for table, name, cols, target, refs, action in definitions:
        op.create_foreign_key(name, table, target, cols, refs, ondelete=action)


_INDEX_CACHE = {}


def _replace_indexes(definitions, obsolete):
    _INDEX_CACHE.clear()
    # Exact catalog definitions preserve older index names on downgrade.
    desired = {name for _, name, _ in definitions}
    inspector = sa.inspect(op.get_bind())
    for table, name, _ in obsolete:
        present = {i['name'] for i in inspector.get_indexes(table)}
        if name not in desired and name in present:
            op.drop_index(name, table_name=table)
    for table, name, statement in definitions:
        if table not in _INDEX_CACHE:
            _INDEX_CACHE[table] = {i['name'] for i in inspector.get_indexes(table)}
        present = _INDEX_CACHE[table]
        if name == 'uq_taller_solicitudes_n_bus_activa_sin_bus_id' and name in present:
            op.drop_index(name, table_name=table)
            present.remove(name)
        if name not in present:
            op.execute(statement)
            present.add(name)


def upgrade():
    connection = op.get_bind()
    _require_postgres(connection)
    # Keep deployment locks bounded; do not leave API traffic queued indefinitely.
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '120s'")
    findings = audit(connection)
    if findings:
        raise RuntimeError('Migración 022 abortada; resolver datos incompatibles mediante migración revisada: ' + repr(findings))
    op.add_column('taller_solicitud_detalles', sa.Column('falla_nombre_snapshot', sa.String(150), nullable=True))
    op.add_column('taller_solicitud_detalles', sa.Column('categoria_nombre_snapshot', sa.String(100), nullable=True))
    op.execute("UPDATE taller_solicitud_detalles d SET falla_nombre_snapshot=f.nombre, categoria_nombre_snapshot=c.nombre FROM fallas_taller f JOIN categorias_falla c ON c.id=f.categoria_id WHERE d.falla_id=f.id")
    op.execute("UPDATE taller_asignacion_fallas SET origen='SUPERVISOR' WHERE origen='SUPERVISION'")
    op.alter_column('buses', 'is_active', existing_type=sa.Boolean(), nullable=False)
    op.alter_column('usuarios', 'rol_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('reportes_neumaticos', 'ruedas', existing_type=sa.JSON(), nullable=False)
    for table, column, expected, _ in DEFAULTS:
        op.alter_column(table, column, server_default=sa.text(expected) if expected else None)
    for table, name, cols in UNIQUES:
        existing = {c['name'] for c in sa.inspect(connection).get_unique_constraints(table)}
        if name not in existing:
            op.create_unique_constraint(name, table, cols)
    _replace_foreign_keys(FOREIGN_KEYS)
    for table, name, expression in CHECKS:
        op.create_check_constraint(name, table, expression)
    _replace_indexes(INDEXES, OLD_INDEXES)
    for table, name, _ in DUPLICATE_UNIQUES:
        existing = {c['name'] for c in sa.inspect(connection).get_unique_constraints(table)}
        if name in existing:
            op.drop_constraint(name, table, type_='unique')


def downgrade():
    _require_postgres(op.get_bind())
    op.execute("SET LOCAL lock_timeout = '5s'")
    _replace_foreign_keys(OLD_FOREIGN_KEYS)
    for table, name, _ in reversed(CHECKS):
        op.drop_constraint(name, table, type_='check')
    # Only constraints introduced here are removed; the pre-existing pauta unique stays.
    for table, name, _ in reversed(UNIQUES):
        if name != 'uq_solicitud_pauta_item':
            op.drop_constraint(name, table, type_='unique')
    _replace_indexes(OLD_INDEXES, INDEXES)
    for table, name, cols in DUPLICATE_UNIQUES:
        op.create_unique_constraint(name, table, cols)
    for table, column, _, previous in DEFAULTS:
        op.alter_column(table, column, server_default=sa.text(previous) if previous else None)
    op.alter_column('buses', 'is_active', existing_type=sa.Boolean(), nullable=True)
    op.alter_column('usuarios', 'rol_id', existing_type=sa.Integer(), nullable=True)
    op.alter_column('reportes_neumaticos', 'ruedas', existing_type=sa.JSON(), nullable=True)
    op.drop_column('taller_solicitud_detalles', 'categoria_nombre_snapshot')
    op.drop_column('taller_solicitud_detalles', 'falla_nombre_snapshot')
